language: node_js
node_js:
  - "node"
script: "npm run-script coveralls"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache:
  directories:
    - "node_modules"
